[package]
name = "chessmate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["godot"]
godot = ["dep:godot"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", optional = true }
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
